
typedef enum {
  PROG = 0, VAR, ARRAY, TO, OF, FUNC, PROC, INT, REAL, BOOL, START, END, IF, THEN, ELSE, WHILE, DO, NOT, AND, OR, DIV, MOD, IDENT, NUM, COLON, SCOLON, COMMA, DOT, LBRA, RBRA, LPAR, RPAR, ASSIGN, LT, LE, GT, GE, EQ, NE, PLUS, MINUS, TIMES, SLASH, TRUE, FALSE, EPSILON, ERROR
} Token;

